import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageBody from "@/components/PageBody";
import PageHeader from "@/components/PageHeader";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Naapp",
  description: "Generated by PW",
};

export interface PageProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<PageProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <PageHeader />
          <PageBody>
            {children}
          </PageBody>
        </Providers>
      </body>
    </html>
  );
}
